"""Minimal type stubs for opencv-python (cv2)."""

from typing import Any, Sequence

INTER_LINEAR: int
INTER_AREA: int
INTER_CUBIC: int

def VideoWriter_fourcc(c1: str, c2: str, c3: str, c4: str) -> int: ...
def resize(src: Any, dsize: tuple[int, int], *, interpolation: int = ...) -> Any: ...

class VideoWriter:
    def __init__(self, filename: str, fourcc: int, fps: float, frameSize: tuple[int, int]) -> None: ...
    def isOpened(self) -> bool: ...
    def write(self, image: Any) -> None: ...
    def release(self) -> None: ...
